import 'viem/window';
export declare function getSubstringAfterFirstPoint(input: string): string;
type EnsFuseName = 'Cannot Unwrap Name' | 'Cannot Burn Fuses' | 'Cannot Transfer' | 'Cannot Set Resolver' | 'Cannot Set Time To Live' | 'Cannot Create Subdomain' | 'Parent Domain Cannot Control' | 'Cannot Approve' | 'Is .eth domain' | 'Can Extend Expiry' | 'Can Do Everything';
export declare const CANNOT_UNWRAP = 1n;
export declare const CANNOT_BURN_FUSES = 2n;
export declare const CANNOT_TRANSFER = 4n;
export declare const CANNOT_SET_RESOLVER = 8n;
export declare const CANNOT_SET_TTL = 16n;
export declare const CANNOT_CREATE_SUBDOMAIN = 32n;
export declare const CANNOT_APPROVE = 64n;
export declare const PARENT_CANNOT_CONTROL: bigint;
export declare const IS_DOT_ETH: bigint;
export declare const CAN_EXTEND_EXPIRY: bigint;
export declare const CAN_DO_EVERYTHING = 0n;
export declare const extractENSFuses: (uint: bigint) => readonly EnsFuseName[];
export declare const fuseNamesToUint: (names: readonly EnsFuseName[]) => number;
export type DomainInfo = {
    isWrapped: boolean;
    nameHash: `0x${string}`;
    owner: `0x${string}`;
    registeryOwner: `0x${string}`;
    data: readonly [`0x${string}`, number, bigint];
    fuses: readonly EnsFuseName[];
    expiry: bigint;
    label: string;
    registered: boolean;
};
export type AccountAddress = `0x${string}`;
export declare const requestAccounts: () => Promise<`0x${string}` | undefined>;
export declare const getAccounts: () => Promise<`0x${string}` | undefined>;
export declare const getDomainInfo: (account: AccountAddress, nameHash: `0x${string}`, label: string, token: `0x${string}`) => Promise<DomainInfo>;
export declare const parentFuseToBurn: "Cannot Unwrap Name";
export declare const doWeNeedToBurnParentFuses: (parentInfo: DomainInfo) => boolean;
export declare const burnParentFuses: (account: AccountAddress, parentInfo: DomainInfo) => Promise<import("viem").TransactionReceipt | undefined>;
export declare const mandatoryChildFusesToBurn: readonly ["Parent Domain Cannot Control"];
export declare const childFusesToBurn: readonly ["Cannot Unwrap Name", "Cannot Burn Fuses", "Cannot Set Resolver", "Cannot Set Time To Live", "Cannot Create Subdomain", "Parent Domain Cannot Control", "Cannot Approve", "Can Extend Expiry"];
export declare const doWeNeedToBurnChildFuses: (childInfo: DomainInfo) => boolean;
export declare const burnChildFuses: (account: AccountAddress, ensLabel: string, childInfo: DomainInfo, parentInfo: DomainInfo) => Promise<import("viem").TransactionReceipt | undefined>;
export declare const wrapDomain: (account: AccountAddress, domainInfo: DomainInfo, subdomain: boolean) => Promise<import("viem").TransactionReceipt | undefined>;
export declare const isValidEnsSubDomain: (subdomain: string) => boolean;
export declare const isChildOwnershipBurned: (childInfo: DomainInfo) => boolean;
export declare const transferChildOwnershipAway: (account: AccountAddress, childInfo: DomainInfo) => Promise<import("viem").TransactionReceipt | undefined>;
export declare const getRightSigningAddress: (transaction: 'wrapParent' | 'wrapChild' | 'parentFuses' | 'childFuses' | 'subDomainOwnership', childInfo: DomainInfo, parentInfo: DomainInfo) => `0x${string}`;
export {};
//# sourceMappingURL=utils.d.ts.map